[tool.ruff]
target-version = "py313"
line-length = 127
indent-width = 4
exclude = [
    "sandbox/*",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
# Aspire to include all DJ rules --JLS
# https://pypi.org/project/flake8-django/
# https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style
ignore = ["DJ001", "DJ006", "EM101"]
select = ["E", "F", "W", "UP", "EM", "DJ"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
